In [1]:
import pandas as pd
import numpy as np

In [2]:
#create list 

ls = [[1, 2, 3], ['a', 'b', 'c'], [4], [5]]
lss = ['string1', 'string2', 'string3', 'string4']
str = ["string"]
#makes into a table-like format with "None" filling in for items not included in obj argument
#NOTE that the rows and columns are labeled with ints
df = pd.DataFrame(ls)
dff = pd.DataFrame(lss)
print(f"{df}\n")
print(dff)
#returns the dimensions of the obj
#as opposed to providing dimensions of obj, when [0] is added, it returns the number of elements in the list only
print(f"shape: {df.shape}")
#returns a tuple of the dimensionality of the DataFrame object   (how many elements, the number of lists)
print(dff.shape)
print(lss[-1:])
print(lss[-3:])
str[1:2]    


   0     1     2
0  1     2     3
1  a     b     c
2  4  None  None
3  5  None  None

         0
0  string1
1  string2
2  string3
3  string4
shape: (4, 3)
(4, 1)
['string4']
['string2', 'string3', 'string4']


[]

In [3]:
#np.zeros(x) creates n-dimensional array of zeros
#these are considered general ndarry creation functions
a = np.zeros(4, int);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.ones((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
#np.random.random_sample(x) creates x number of rand float64 numbers and place them in array
a = np.random.random_sample(0); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.zeros(4) :   a = [0 0 0 0], a shape = (4,), a data type = int64
np.zeros(4,) :  a = [1. 1. 1. 1.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [], a shape = (0,), a data type = float64


In [4]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.65159536 0.31386205 0.63785259 0.68099844], a shape = (4,), a data type = float64


In [5]:
#indexing and slicing vectors
a = np.array([1,2,3,4])
print(f"a is {a}")
#negate elements of a
b = -a
print(f"b is {b}")
#working with tuples
atuple = np.array((1,2,3), dtype=np.int32)
print(atuple)


a is [1 2 3 4]
b is [-1 -2 -3 -4]
[1 2 3]


In [6]:
#NumPy's array creation funcitons
#1D array of incrementing values
oneDimenstion_1 = np.arange(1,10)
print(oneDimenstion_1)
oneDimention_2 = np.arange(2,3,0.1) #how does this work?
print(oneDimention_2)


[1 2 3 4 5 6 7 8 9]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [9]:
#2d array creation functions
#np.eye creates the arrays within arrays with the parameter being the number of elements. the el will be 1s and 0s
twoDimention_1 = np.eye(3)
print(f"{twoDimention_1} \n ")
#add a second argument to dictate the # of el in each array
twoDimension_2 = np.eye(3, 5)
print(f" {twoDimension_2} \n")
#creating a 2D square array for linear algebra
#can return values along the diagnoal el
square_1 = np.diag([1,2,3]) #requires obj
print(f"{square_1} \n")
#can create vandermode matrices: each col of matrix is a decreasing power of the input 1D array, x where the
    #highest polynomial order is n-1. helpful for creating linear least squares models
vander_1 = np.vander([1,2,3,4,5,6,7,8,9], 3) #second param dictates how many squared el in each array
print(vander_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]] 

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]
 [36  6  1]
 [49  7  1]
 [64  8  1]
 [81  9  1]]
